baseURL = "http://pbinspanish.github.io"
languageCode = "en-ca"
title = "Josiah Henson"
theme = "josiahstheme"
publishDir = "pbinspanish.github.io"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 3

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "native"
    tabWidth = 4